#\!/usr/bin/env python3
"""
Generate .cursor/rules/operational-state.mdc from live knowledge layer artifacts.

Run via cron (post-pipeline) or manually to keep Cursor's operational context fresh.
The generated file has alwaysApply: true so every session gets current state without
explicit MCP calls.

Usage:
    python3 tools/generate_operational_state_rule.py

Output:
    .cursor/rules/operational-state.mdc (overwritten each run)
"""

import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path


def _resolve_artifacts_dir() -> Path:
    """Resolve artifacts/ops directory."""
    if env := os.environ.get("HERMES_REPO"):
        return Path(env) / "artifacts" / "ops"
    # Fallback: relative to this script
    return Path(__file__).resolve().parent.parent / "artifacts" / "ops"


def _resolve_output_path() -> Path:
    """Resolve .cursor/rules/ output path."""
    if env := os.environ.get("HERMES_REPO"):
        return Path(env) / ".cursor" / "rules" / "operational-state.mdc"
    return Path(__file__).resolve().parent.parent / ".cursor" / "rules" / "operational-state.mdc"


def _read_json(path: Path) -> dict | list | None:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def _read_text(path: Path) -> str | None:
    try:
        return path.read_text(encoding="utf-8")
    except OSError:
        return None


def generate() -> str:
    """Generate the .mdc file content from live artifacts."""
    artifacts = _resolve_artifacts_dir()
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    sections = []

    # Header
    sections.append(f"""---
description: AUTO-GENERATED operational state — regenerated by tools/generate_operational_state_rule.py. Do not edit manually.
globs: []
alwaysApply: true
---

# Operational State (generated {now})

**This file is auto-generated. Do not edit manually.**
**Source:** `tools/generate_operational_state_rule.py`
**Refresh:** After each daily pipeline run or on demand.
""")

    # Latest state
    state = _read_json(artifacts / "knowledge_layer" / "latest_state.json")
    if state:
        as_of = state.get("as_of", "unknown")
        git_head = state.get("git_head", state.get("head", "unknown"))
        cron_active = state.get("cron_active", "?")
        cron_suppressed = state.get("cron_suppressed", "?")
        contradictions = state.get("hard_contradictions", state.get("contradictions", 0))
        snapshot_date = state.get("latest_snapshot", state.get("snapshot_date", "unknown"))

        sections.append(f"""## Fleet State

| Field | Value |
|-------|-------|
| As of | {as_of} |
| Git HEAD | `{git_head}` |
| Cron active | {cron_active} |
| Cron suppressed | {cron_suppressed} |
| Hard contradictions | {contradictions} |
| Latest snapshot | {snapshot_date} |
""")

        # Extract freeze status if present
        freeze = state.get("architecture_freeze") or state.get("freeze")
        if freeze:
            sections.append(f"""## Architecture Freeze

**Status:** ACTIVE
**Details:** {freeze}
""")
        else:
            sections.append("""## Architecture Freeze

**Status:** Not active
""")
    else:
        sections.append("""## Fleet State

**WARNING:** `latest_state.json` not found or unreadable. Run `tools/build_hermes_knowledge_layer.py` to regenerate.
""")

    # Held spec ledger
    held = _read_json(artifacts / "held_spec_ledger" / "latest.json")
    if held:
        if isinstance(held, dict):
            items = list(held.items())
        elif isinstance(held, list):
            items = [(item.get("id", f"item_{i}"), item) for i, item in enumerate(held)]
        else:
            items = []

        if items:
            sections.append("## Held Specifications\n")
            sections.append("| ID | Status | Note |")
            sections.append("|-----|--------|------|")
            for spec_id, detail in items:
                if isinstance(detail, dict):
                    status = detail.get("status", "HELD")
                    note = detail.get("note", detail.get("reason", ""))
                else:
                    status = str(detail)
                    note = ""
                sections.append(f"| {spec_id} | {status} | {note} |")
            sections.append("")
        else:
            sections.append("## Held Specifications\n\nNone.\n")
    else:
        sections.append("## Held Specifications\n\n*Ledger not found.*\n")

    # Contradiction count
    contradiction_path = artifacts / "contradiction_ledger" / "latest.md"
    if contradiction_path.exists():
        content = _read_text(contradiction_path) or ""
        hard = sum(1 for line in content.splitlines()
                  if "hard" in line.lower() and line.strip().startswith("-"))
        drift = sum(1 for line in content.splitlines()
                   if "drift" in line.lower() and line.strip().startswith("-"))
        sections.append(f"""## Contradictions

- Hard: {hard}
- Possible drift: {drift}
""")
        if hard > 0:
            sections.append("**ACTION REQUIRED:** Hard contradictions must be resolved before proceeding with governed changes.\n")

    return "\n".join(sections)


def main():
    output_path = _resolve_output_path()
    output_path.parent.mkdir(parents=True, exist_ok=True)

    content = generate()
    output_path.write_text(content, encoding="utf-8")
    print(f"Generated: {output_path} ({len(content)} bytes)")


if __name__ == "__main__":
    main()
